# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Siddique Traders/ariane/ariane.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Siddique Traders/ariane/ariane.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Siddique Traders/ariane/ariane.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/rvfi_types.svh}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cvxif_types.svh}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/rvfi_types.svh}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cvxif_types.svh}}]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv32a60x_config_pkg_deprecated.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv32a65x_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv32a6_embedded_config_pkg_deprecated.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv32a6_ima_sv32_fpga_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv32a6_imac_sv0_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv32a6_imac_sv32_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv32a6_imafc_sv32_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imafdc_sv39_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imafdc_sv39_wb_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imafdch_sv39_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imafdch_sv39_wb_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_imafdcv_sv39_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/cv64a6_mmu_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/riscv_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/ariane_pkg.sv}
  {C:/Users/Siddique Traders/ariane-cva6/core/cvfpu/src/fpnew_pkg.sv}
  {C:/Users/Siddique Traders/ariane/ariane.srcs/sources_1/new/fpnew_pkg.sv}
  {C:/Users/Siddique Traders/ariane/ariane.srcs/sources_1/imports/pkg/cf_math_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/alu.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/amo_buffer.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/ariane_regfile_ff.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/ariane_regfile_fpga.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/axi_adapter.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/axi_shim.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/frontend/bht.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/branch_unit.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/frontend/btb.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/build_config_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/std_cache_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/cache_ctrl.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/commit_stage.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/compressed_decoder.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/controller.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/csr_buffer.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/csr_regfile.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/include/wt_cache_pkg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6_accel_first_pass_decoder_stub.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6_fifo_v3.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/cva6_hpdcache_if_adapter.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/cva6_hpdcache_subsystem.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/cva6_hpdcache_wrapper.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/cva6_icache.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/cva6_icache_axi_wrapper.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6_mmu/cva6_mmu.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6_mmu/cva6_ptw.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6_rvfi_probes.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6_mmu/cva6_shared_tlb.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6_mmu/cva6_tlb.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cvxif_compressed_if_driver.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cvxif_fu.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cvxif_issue_register_commit_if_driver.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/decoder.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/ex_stage.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/exp_backoff.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/fpu_wrap.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/frontend/frontend.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/id_stage.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/frontend/instr_queue.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/instr_realign.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/frontend/instr_scan.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/issue_read_operands.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/issue_stage.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/lfsr.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/lfsr_8bit.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/load_store_unit.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/load_unit.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/lsu_bypass.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/lzc.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/macro_decoder.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/miss_handler.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/mult.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/multiplier.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/perf_counters.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/popcount.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/frontend/ras.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/rr_arb_tree.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/scoreboard.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/serdiv.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/shift_reg.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/deprecated/sram.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/std_cache_subsystem.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/std_nbdcache.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/store_buffer.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/store_unit.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/stream_arbiter.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/stream_arbiter_flushable.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/stream_demux.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/stream_mux.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/tag_cmp.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/pkg/unread.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/wt_axi_adapter.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/wt_cache_subsystem.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/wt_dcache.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/wt_dcache_ctrl.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/wt_dcache_mem.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/wt_dcache_missunit.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cache_subsystem/wt_dcache_wbuffer.sv}
  {C:/Users/Siddique Traders/VIVADOPROJECTS/ariane/cva6.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Siddique Traders/Downloads/Arty-A7-100-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Siddique Traders/Downloads/Arty-A7-100-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top cva6 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cva6.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cva6_utilization_synth.rpt -pb cva6_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
